### PR TITLE
Add grape support

### PR DESCRIPTION
**Pull request by matsimitsu**

### CODE REVIEW

**Comment by jeromegn** [comment]
These seem like good changes. I'd love to start using the 1.x gem in my Grape apps.

**Comment by matsimitsu** [comment]
Hi @jeromegn We're planning on releasing it this week. (we've been waiting for feedback from customers who are trying it out to verify everything works ok).

**Comment by thijsc** [comment]
Merging this, it will be in the `1.1.0` beta release that's coming out shortly.

**Comment by jeromegn** [comment]
What's the status on that beta release? Can't wait :)

**Comment by thijsc** [comment]
It's in the `1.1.0.beta` gem that's currently out :-). The documentation for it is here: http://docs.appsignal.com/getting-started/supported-frameworks.html#grape

**Comment by jeromegn** [comment]
Oh, my bad.

Ok, I just set it up on a few of our grape apps, thanks! Will let you know if it catches fire.

**Comment by thijsc** [comment]
@jeromegn No worries, let us know if it works for you!

**Pull request merged**
