### PR TITLE
Add proxy configuration

### PR DESCRIPTION
**Pull request by brunoadacosta**

### CODE REVIEW

**Comment by matsimitsu** [comment]
Awesome, thanks! 

We'll merge this in before the next release :)

**Comment by brunoadacosta** [comment]
nice :) thanks

**Comment by thijsc** [comment]
Thanks a lot for the pull! I ended up implementing it in a slightly different way to make sure that behavior does not change for customers that do not use a proxy. That's in 184231625482a296b55f8c49fa78d111740e3eb3. I just published to `0.11.13.beta.0` release. Could you try that?

**Comment by brunoadacosta** [comment]
@thijsc testing now..

**Comment by brunoadacosta** [comment]
@thijsc it's working, nice job! thanks

**Comment by thijsc** [comment]
Thanks for testing!

**Pull request closed without merging**
